---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      annotations:
        commit-sha: "{{GIT_SHA}}"
      labels:
        app: website
    spec:
      containers:
        - image: git.tbrnt.ch/feuerwehrurdorf/website:latest
          imagePullPolicy: Always
          name: nginx
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 300m
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config-volume
          configMap:
            name: nginx-confs
